pinboardpro/urls.py
from django.conf.urls import url
from django.contrib import admin

from pinboard import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]


urlpatterns +=[
    url(r'^$', views.IndexListView.as_view(), name= 'index'),
    url(r'^(?P<pk>\d+)/$', views.PinDetailView.as_view() , name='detail'),
    url(r'^csu$', views.createsuperuserview),

]

pinboard/models.py
from random import choice

from django.db import models
from django.utils import timezone

color_list = ['LightPink',
              'LightGreen',
              'yellow',
              'YellowGreen',
              'AntiqueWhite',
              'Beige',
              'Cornsilk',
              'Azure',
              'LavenderBlush',
              'MistyRose',
              ]

def get_color():
    return choice(color_list)

def get_range():
    return choice(list(range(-3,4)))

def get_font():
    return choice(['BenSenHandwriting', 'Sharifa_03-09-2005'])


class Pin(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tag = models.ManyToManyField('Tag', blank=True)

    style_color = models.CharField(max_length=50, default=get_color, blank=True)
    style_transform_range = models.IntegerField(default=get_range, blank=True)
    style_font = models.CharField(max_length=50, default=get_font, blank=True)

    def get_tags(self):
        return ', '.join([tag.name for tag in self.tag.all() ])

    def __str__(self):
        return self.text[:30]

    class Meta:
        ordering = ['-updated_at','-created_at']


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

pinboard/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic

from .models import Pin, Tag


class IndexListView(generic.ListView):
    model = Pin
    template_name = 'pinboard/index.html'
    paginate_by = 12


class PinDetailView(generic.DetailView):
    model = Pin
    template_name = 'pinboard/pin_detail.html'

def createsuperuserview(request):
    try:
        import os
        from django.contrib.auth.models import User

        username  = os.getenv('USERNAME')
        email     = os.getenv('EMAIL')
        password  = os.getenv('PASSWORD')

        User.objects.create_superuser(username,email,password)

        return HttpResponse("User {} created".format(username))
    except Exception as e:
        return HttpResponse("{}".format(e))

pinboard/templates/pinboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Pinboard</title>{% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="wrapper">
<div class="">
    {% block content %}
    {% endblock %}
</div>
{% include 'pinboard/partials/pagination.html' %}

</body>
</html>

pinboard/templates/pinboard/index.html
{% extends 'pinboard/base.html' %}

{% block content %}

    {% for pin in pin_list %}
        <p class="note-wrap" style=" font-family:{{ pin.style_font }};
                                     background: {{ pin.style_color }};
                                    -webkit-transform: rotate({{ pin.style_transform_range }}deg);
                                    -moz-transform: rotate({{ pin.style_transform_range }}deg);
                                    -o-transform: rotate({{ pin.style_transform_range }}deg);
                                    -ms-transform: rotate({{ pin.style_transform_range }}deg);
                                    transform: rotate({{ pin.style_transform_range }}deg); ">

            {{ pin.text|truncatewords:20 }}<br>
            <a href="{% url 'detail' pin.id %}">বিস্তারিত</a>

        </p>
    {% endfor %}

{% endblock %}

pinboard/templates/pinboard/partials/pagination.html
{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}

pinboard/templates/pinboard/pin_detail.html
{% extends 'pinboard/base.html' %}

{% block content %}
<div class="clearfix">
    <div style="font-family:'BenSenHandwriting' ">
        {{ pin.text|linebreaks }}<hr /><br />

        লেখা হয়েছে : {{ pin.created_at }}<br />
        আপডেট হয়েছে : {{ pin.updated_at }}<br />
    {% if pin.tag.all %}
       <p> ট্যাগ
        :{% for tag in pin.tag.all %} {{ tag }}{% if not forloop.last %}, {% endif %}{% endfor %}
       </p>
    {% endif %}
    <br /><a href="{% url 'index' %}" class="link">হোম</a>
    </div>
</div>


{% endblock %}